### ISSUE TITLE
Spacy BERT model failed to download the model bin and config

### ISSUE THREAD

**Issue by shaked571** [explosion/spacy-pytorch-transformers#15]
I am working in behind proxy, hence I can't download Spacy's model from my code.
So, I use to direct download my model and install them manually(`pip install de_pytt_bertbasecased_lg-2.1.0.tar.gz`)
With the previous models I used the following code to init my base model:

```
import en_core_web_md  
nlp = en_core_web_md.load()
```
When I tried to do the same with the BERT model:
```
import en_pytt_bertbaseuncased_lg  
nlp = en_pytt_bertbaseuncased_lg.load()
```
It seem that spacy is trying to reach out to in the model initialization in order to get the model's meat data and the vector's weights, and because I am behind proxy, it fails:
```
Couldn't reach server at 'https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-config.json' to download pretrained model configuration file.
Couldn't reach server at 'https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-pytorch_model.bin' to download pretrained weights.
Traceback (most recent call last):
  File "C:/path/train.py", line 7, in <module>
    nlp = en_pytt_bertbaseuncased_lg.load()
  File "C:\env\lib\site-packages\en_pytt_bertbaseuncased_lg\__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "C:\env\lib\site-packages\spacy\util.py", line 196, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "C:\env\lib\site-packages\spacy\util.py", line 179, in load_model_from_path
    return nlp.from_disk(model_path)
  File "C:\env\lib\site-packages\spacy\language.py", line 832, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "C:\env\lib\site-packages\spacy\util.py", line 636, in from_disk
    reader(path / key)
  File "C:\env\lib\site-packages\spacy\language.py", line 827, in <lambda>
    p, exclude=["vocab"]
  File "pipes.pyx", line 222, in spacy.pipeline.pipes.Pipe.from_disk
  File "C:\env\lib\site-packages\spacy\util.py", line 636, in from_disk
    reader(path / key)
  File "pipes.pyx", line 211, in spacy.pipeline.pipes.Pipe.from_disk.load_model
  File "C:\env\lib\site-packages\spacy_pytorch_transformers\tok2vec.py", line 63, in Model
    nO = pytt_model.nO
  File "C:\env\lib\site-packages\spacy_pytorch_transformers\wrapper.py", line 37, in nO
    return self._model.config.hidden_size
AttributeError: 'NoneType' object has no attribute 'config'
```
Any solution?

**Comment by ines** [comment]
This is very strange – the wrapper shouldn't have to connect to Hugging Face's bucket at all and the package should include everything it needs 🤔 This was one of the main motivations for repackaging the models. So it seems like *something* is going wrong here.

**Comment by einarbmag** [comment]
Getting error "type object 'BertModel' has no attribute 'config'" now instead (sorry for not posting whole stack trace... Also behind proxy :(  )

**Comment by alpinoblack** [comment]
@einarbmag This what I'm having now as well
BTW It's also happening in the german BERT model.

seem like a bountiful of of the `pytt_model` parameters didn't initialize correctly.
i.e. `input_shape`, `max_length`,`out_put_shape` and of course `n0`

**Comment by jameszlj** [comment]
nlp = spacy.load("en_pytt_bertbaseuncased_lg") ==> type object 'BertModel' has no attribute 'config'  Is there a solution?
