### ISSUE TITLE
NameError: name 'gpu_ops' is not defined

### ISSUE THREAD

**Issue by miluki01** [explosion/spacy-pytorch-transformers#24]
Hi,
I ran the example: train_textcat.py and got the issue
```
Loaded model 'en_pytt_bertbaseuncased_lg'
Loading IMDB data...
Using 100 training docs, 2000 evaluation)
Extracted 1192 training sents
Training the model...
LOSS      P       R       F
Traceback (most recent call last):
  File "train_textcat.py", line 201, in <module>
    plac.call(main)
  File "/data/miniconda3/envs/pt/lib/python3.7/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/data/miniconda3/envs/pt/lib/python3.7/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "train_textcat.py", line 83, in main
    nlp.update(texts, annotations, sgd=optimizer, drop=0.1, losses=losses)
  File "/data/miniconda3/envs/pt/lib/python3.7/site-packages/spacy_pytorch_transformers/language.py", line 96, in update
    component_cfg=component_cfg,
  File "/data/miniconda3/envs/pt/lib/python3.7/site-packages/spacy/language.py", line 471, in update
    proc.update(docs, golds, sgd=get_grads, losses=losses, **kwargs)
  File "pipes.pyx", line 968, in spacy.pipeline.pipes.TextCategorizer.update
  File "/data/miniconda3/envs/pt/lib/python3.7/site-packages/thinc/neural/_classes/feed_forward.py", line 46, in begin_update
    X, inc_layer_grad = layer.begin_update(X, drop=drop)
  File "/data/miniconda3/envs/pt/lib/python3.7/site-packages/thinc/neural/pooling.py", line 30, in begin_update
    res, bp_res = func.begin_update((X, lengths))
  File "/data/miniconda3/envs/pt/lib/python3.7/site-packages/thinc/neural/pooling.py", line 53, in mean_pool
    output = ops.mean_pool(X, lengths)
  File "ops.pyx", line 947, in thinc.neural.ops.CupyOps.mean_pool
NameError: name 'gpu_ops' is not defined
```
I already installed spacy[cuda101]
What can I fix that?
Thanks

**Comment by ines** [comment]
That error usually means that the GPU dependencies weren't installed correctly. There's no `[cuda101]` marker, so that's likely the problem: https://github.com/explosion/spaCy/blob/master/setup.py#L241-L246
