### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'`

### ISSUE THREAD

**Issue by igormis** [explosion/spacy-pytorch-transformers#28]
When running the following command for training on GPU:
`
python train_textcat.py en_pytt_xlnetbasecased_lg -o ./results
`
I get an error (after some iterations):
`
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'`
`
Here is the traceback:
Using GPU
Loaded model 'en_pytt_xlnetbasecased_lg'
Loading IMDB data...
Using 23000 training docs, 2000 evaluation)
Extracted 284175 training sents
Training the model...
LOSS 	  P  	  R  	  F  
Traceback (most recent call last):
  File "train_textcat.py", line 207, in <module>
    plac.call(main)
  File "/usr/local/lib/python3.6/dist-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/usr/local/lib/python3.6/dist-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "train_2.py", line 87, in main
    nlp.update(texts, annotations, sgd=optimizer, drop=0.1, losses=losses)
  File "/usr/local/lib/python3.6/dist-packages/spacy_pytorch_transformers/language.py", line 83, in update
    docs, drop=drop, **component_cfg.get("pytt_tok2vec", {})
  File "/usr/local/lib/python3.6/dist-packages/spacy_pytorch_transformers/pipeline/tok2vec.py", line 129, in begin_update
    outputs, backprop = self.model.begin_update(docs, drop=drop)
  File "/usr/local/lib/python3.6/dist-packages/spacy_pytorch_transformers/model_registry.py", line 288, in sentence_fwd
    words_per_sent = [len(s._.pytt_word_pieces) for s in sents]
  File "/usr/local/lib/python3.6/dist-packages/spacy_pytorch_transformers/model_registry.py", line 288, in <listcomp>
    words_per_sent = [len(s._.pytt_word_pieces) for s in sents]
  File "/usr/local/lib/python3.6/dist-packages/spacy/tokens/underscore.py", line 38, in __getattr__
    return getter(self._obj)
  File "/usr/local/lib/python3.6/dist-packages/spacy_pytorch_transformers/language.py", line 189, in span_getter
    return doc_values[start:end+1]
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'`
`

**Comment by ines** [comment]
This should have been fixed in v0.1.1: https://github.com/explosion/spacy-pytorch-transformers/releases/tag/v0.1.1

**Comment by igormis** [comment]
Yes, fixed but later on, another issue:
`
   plac.call(main)
  File "/usr/local/lib/python3.6/dist-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/usr/local/lib/python3.6/dist-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "train_2.py", line 87, in main
    nlp.update(texts, annotations, sgd=optimizer, drop=0.1, losses=losses)
  File "/usr/local/lib/python3.6/dist-packages/spacy_pytorch_transformers/language.py", line 83, in update
    docs, drop=drop, **component_cfg.get("pytt_tok2vec", {})
  File "/usr/local/lib/python3.6/dist-packages/spacy_pytorch_transformers/pipeline/tok2vec.py", line 129, in begin_update
    outputs, backprop = self.model.begin_update(docs, drop=drop)
  File "/usr/local/lib/python3.6/dist-packages/spacy_pytorch_transformers/model_registry.py", line 290, in sentence_fwd
    assert sum(words_per_doc) == sum(words_per_sent)
`

**Comment by honnibal** [comment]
Could you try the `feature/textpair` branch? Sorry for the instability.

**Comment by igormis** [comment]
I did
`
! git clone https://github.com/explosion/spacy-pytorch-transformers.git
% cd spacy-pytorch-transformers/
! git fetch https://github.com/explosion/spacy-pytorch-transformers.git feature/textpair:feature/textpair
! git checkout feature/textpair
`
Bu then should I run setup.py and with which options to include cuda100 extra?

**Comment by ines** [comment]
@igormis I think you can just install the [extra requirements](https://github.com/explosion/spacy-pytorch-transformers/blob/master/setup.py#L48) for your version manually before installing the othe requirements via `pip install -r requirements.txt`.
