### ISSUE TITLE
RuntimeError: CUDA out of memory?

### ISSUE THREAD

**Issue by igormis** [explosion/spacy-pytorch-transformers#30]
I am trying to execute the script:
`
python train_textcat.py en_pytt_xlnetbasecased_lg
`
Where instead of loading the whole imdb_dataset, for testing I am using only
`
Using 200 training docs, 100 evaluation)
Extracted 2565 training sents
`
However at 8% I getting an error:
`
RuntimeError: CUDA out of memory. Tried to allocate 78.00 MiB (GPU 0; 11.17 GiB total capacity; 9.47 GiB already allocated;
`
which is very strange as I have 12 GB free before execution.

here is the traceback:
`
Traceback (most recent call last):
  File "train_2.py", line 210, in <module>
    plac.call(main)
  File "/usr/local/lib/python3.6/dist-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/usr/local/lib/python3.6/dist-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "train_2.py", line 87, in main
    nlp.update(texts, annotations, sgd=optimizer, drop=0.1, losses=losses)
  File "/usr/local/lib/python3.6/dist-packages/spacy_pytorch_transformers/language.py", line 83, in update
    docs, drop=drop, **component_cfg.get("pytt_tok2vec", {})
  File "/usr/local/lib/python3.6/dist-packages/spacy_pytorch_transformers/pipeline/tok2vec.py", line 129, in begin_update
    outputs, backprop = self.model.begin_update(docs, drop=drop)
  File "/usr/local/lib/python3.6/dist-packages/spacy_pytorch_transformers/model_registry.py", line 291, in sentence_fwd
    acts, bp_acts = layer.begin_update(sents, drop=drop)
  File "/usr/local/lib/python3.6/dist-packages/thinc/neural/_classes/feed_forward.py", line 46, in begin_update
    X, inc_layer_grad = layer.begin_update(X, drop=drop)
  File "/usr/local/lib/python3.6/dist-packages/spacy_pytorch_transformers/model_registry.py", line 223, in apply_model_to_batches
    return model.begin_update(inputs, drop=drop)
  File "/usr/local/lib/python3.6/dist-packages/spacy_pytorch_transformers/wrapper.py", line 87, in begin_update
    y_var = self._model(**model_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_transformers/modeling_xlnet.py", line 985, in forward
    attentions = tuple(t.permute(2, 3, 0, 1).contiguous() for t in attentions)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_transformers/modeling_xlnet.py", line 985, in <genexpr>
    attentions = tuple(t.permute(2, 3, 0, 1).contiguous() for t in attentions)
RuntimeError: CUDA out of memory. Tried to allocate 78.00 MiB (GPU 0; 11.17 GiB total capacity; 9.47 GiB already allocated; 46.56 MiB free; 1.26 GiB cached)
Error in sys.excepthook:

`

**Comment by honnibal** [comment]
We've been working on the library quite actively over the last week to try to sort out the various problems. We'll soon be merging the branch `feature/textpair` into master.

I've been training running the `train_textcat.py` script successfully with the XLNet model on a Tesla V100. I think that has the same amount of memory as the card you're using, so it should work.

One thing we'd like to support that we don't currently is fp16. I think that will help the memory pressure a lot.

**Comment by igormis** [comment]
ok, tnx, waiting for the branch

**Comment by igormis** [comment]
Still there are problems with the memory with not so big dataset. The size of the dataset is:
Using 2060 training docs, 514 evaluation in the first iteration after 30% training the RuntimeError is CUDA out of memory. It is from modeling_xlnet.py, Here is the whole traceback:
`
Traceback (most recent call last):
  File "train_textcat_spam.py", line 246, in <module>
    plac.call(main)
  File "/usr/local/lib/python3.6/dist-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/usr/local/lib/python3.6/dist-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "train_textcat_spam.py", line 101, in main
    nlp.update(texts, annotations, sgd=optimizer, drop=0.1, losses=losses)
  File "/content/spacy-pytorch-transformers/spacy_pytorch_transformers/language.py", line 98, in update
    docs, drop=drop, **component_cfg.get("pytt_tok2vec", {})
  File "/content/spacy-pytorch-transformers/spacy_pytorch_transformers/pipeline/tok2vec.py", line 129, in begin_update
    outputs, backprop = self.model.begin_update(docs, drop=drop)
  File "/content/spacy-pytorch-transformers/spacy_pytorch_transformers/model_registry.py", line 344, in sentence_fwd
    acts, bp_acts = layer.begin_update(sents, drop=drop)
  File "/usr/local/lib/python3.6/dist-packages/thinc/neural/_classes/feed_forward.py", line 46, in begin_update
    X, inc_layer_grad = layer.begin_update(X, drop=drop)
  File "/content/spacy-pytorch-transformers/spacy_pytorch_transformers/model_registry.py", line 287, in apply_model_to_batches
    Y, get_dX = model.begin_update(RaggedArray(X, lengths), drop=drop)
  File "/content/spacy-pytorch-transformers/spacy_pytorch_transformers/wrapper.py", line 96, in begin_update
    y_var = self._model(**model_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_transformers/modeling_xlnet.py", line 965, in forward
    head_mask=head_mask[i])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_transformers/modeling_xlnet.py", line 584, in forward
    output_h = self.ff(output_h)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_transformers/modeling_xlnet.py", line 560, in forward
    output = self.activation_function(output)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_transformers/modeling_xlnet.py", line 184, in gelu
    cdf = 0.5 * (1.0 + torch.tanh(math.sqrt(2 / math.pi) * (x + 0.044715 * torch.pow(x, 3))))
`

**Comment by alejandrojcastaneira** [comment]
To enable fp16 in pytorch we have been using the [apex](https://github.com/NVIDIA/apex) library, in fact decreases the processing time and memory footprint considerably.

**Comment by igormis** [comment]
I have installed Apex with CUDA and C++ extensions but still the error remains on this row:
`
File "/usr/local/lib/python3.6/dist-packages/pytorch_transformers/modeling_xlnet.py", line 184, in gelu
    cdf = 0.5 * (1.0 + torch.tanh(math.sqrt(2 / math.pi) * (x + 0.044715 * torch.pow(x, 3))))
`
Any suggestions?

**Comment by igormis** [comment]
Actually now the error is in:
`
  File "/usr/local/lib/python3.6/dist-packages/pytorch_transformers/modeling_xlnet.py", line 442, in post_attention
    attn_out = torch.einsum('ibnd,hnd->ibh', attn_vec, self.o)
  File "/usr/local/lib/python3.6/dist-packages/torch/functional.py", line 211, in einsum
    return torch._C._VariableFunctions.einsum(equation, operands)
`

**Comment by igormis** [comment]
I have also tried to change the sensor type in the script:
`
if is_using_gpu:
        torch.set_default_tensor_type("torch.cuda.HalfTensor")
`
but the expectancy is FloatTensor:
`
  File "/usr/local/lib/python3.6/dist-packages/pytorch_transformers/modeling_xlnet.py", line 841, in relative_positional_encoding
    pos_emb = self.positional_embedding(fwd_pos_seq, inv_freq, bsz)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_transformers/modeling_xlnet.py", line 798, in positional_embedding
    sinusoid_inp = torch.einsum('i,d->id', pos_seq, inv_freq)
  File "/usr/local/lib/python3.6/dist-packages/torch/functional.py", line 211, in einsum
    return torch._C._VariableFunctions.einsum(equation, operands)
RuntimeError: expected backend CUDA and dtype Float but got backend CUDA and dtype Half
`

**Comment by igormis** [comment]
In the modeling_xlnet.py there is this line:
```python
head_mask = head_mask.to(dtype=next(self.parameters()).dtype) # switch to fload if need + fp16 compatibility
```
How to change it?
