### ISSUE TITLE
AttributeError: 'SerializableXLNetTokenizer' object has no attribute 'vocab_file'

### ISSUE THREAD

**Issue by igormis** [explosion/spacy-pytorch-transformers#32]
After testing the script `train_textcat.py ` on the branch `feature/textpair ` everything with the training seems ok now. However, the model cannot be saved at the end, here is the traceback:

```
Traceback (most recent call last):
  File "train_textcat.py", line 237, in <module>
    plac.call(main)
  File "/usr/local/lib/python3.6/dist-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/usr/local/lib/python3.6/dist-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "train_textcat.py", line 121, in main
    nlp.to_disk(output_dir)
  File "/usr/local/lib/python3.6/dist-packages/spacy/language.py", line 796, in to_disk
    util.to_disk(path, serializers, exclude)
  File "/usr/local/lib/python3.6/dist-packages/spacy/util.py", line 627, in to_disk
    writer(path / key)
  File "/usr/local/lib/python3.6/dist-packages/spacy/language.py", line 794, in <lambda>
    serializers[name] = lambda p, proc=proc: proc.to_disk(p, exclude=["vocab"])
  File "pipes.pyx", line 201, in spacy.pipeline.pipes.Pipe.to_disk
  File "/usr/local/lib/python3.6/dist-packages/spacy/util.py", line 627, in to_disk
    writer(path / key)
  File "pipes.pyx", line 199, in spacy.pipeline.pipes.Pipe.to_disk.lambda6
  File "/content/spacy-pytorch-transformers/spacy_pytorch_transformers/_tokenizers.py", line 60, in to_bytes
    self.prepare_for_serialization()
  File "/content/spacy-pytorch-transformers/spacy_pytorch_transformers/_tokenizers.py", line 313, in prepare_for_serialization
    vocab_path = Path(self.vocab_file)
AttributeError: 'SerializableXLNetTokenizer' object has no attribute 'vocab_file'
```

**Comment by ines** [comment]
Could you run `pip list` and double-check that you have the latest version of the model XLNet model package installed?

**Comment by igormis** [comment]
I have:
spacy-pytorch-transformers 0.1.1
and install xlnet model using
python -m spacy download en_pytt_xlnetbasecased_lg

**Comment by igormis** [comment]
en_pytt_xlnetbasecased_lg==2.1.1 from https://github.com/explosion/spacy-models/releases/download/en_pytt_xlnetbasecased_lg-2.1.1/en_pytt_xlnetbasecased_lg-2.1.1.tar.gz#egg=en_pytt_xlnetbasecased_lg==2.1.1 in /usr/local/lib/python3.6/dist-packages (2.1.1)
