### ISSUE TITLE
TypeError: a bytes-like object is required, not 'dict'

### ISSUE THREAD

**Issue by jameszlj** [explosion/spacy-pytorch-transformers#58]
Under your guidance，is latest version(win10 env)：
spacy =2.1.8
torch =1.2.0
spacy-pytorch-transformers=0.4.0
en_pytt_bertbaseuncased_lg=2.1.1

result is not good:

>>> import spacy
>>> nlp = spacy.load("D:\spacy_model\en_pytt_bertbaseuncased_lg-2.1.1")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Win10\Envs\Fine_py3\lib\site-packages\spacy\__init__.py", line 27, in load
    return util.load_model(name, **overrides)
  File "C:\Users\Win10\Envs\Fine_py3\lib\site-packages\spacy\util.py", line 136, in load_model
    return load_model_from_path(Path(name), **overrides)
  File "C:\Users\Win10\Envs\Fine_py3\lib\site-packages\spacy\util.py", line 179, in load_model_from_path
    return nlp.from_disk(model_path)
  File "C:\Users\Win10\Envs\Fine_py3\lib\site-packages\spacy\language.py", line 836, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "C:\Users\Win10\Envs\Fine_py3\lib\site-packages\spacy\util.py", line 636, in from_disk
    reader(path / key)
  File "C:\Users\Win10\Envs\Fine_py3\lib\site-packages\spacy\language.py", line 831, in <lambda>
    p, exclude=["vocab"]
  File "pipes.pyx", line 222, in spacy.pipeline.pipes.Pipe.from_disk
  File "C:\Users\Win10\Envs\Fine_py3\lib\site-packages\spacy\util.py", line 636, in from_disk
    reader(path / key)
  File "pipes.pyx", line 213, in spacy.pipeline.pipes.Pipe.from_disk.load_model
  File "C:\Users\Win10\Envs\Fine_py3\lib\site-packages\thinc\neural\_classes\model.py", line 362, in from_bytes
    layer.from_bytes(weights[i])
  File "C:\Users\Win10\Envs\Fine_py3\lib\site-packages\spacy_pytorch_transformers\wrapper.py", line 259, in from_bytes
    filelike = BytesIO(data)
TypeError: a bytes-like object is required, not 'dict'

**Comment by honnibal** [comment]
Can you try again with spaCy 2.1.8, if the version you gave wasn't a typo?

I've seen some people report errors like this and I don't understand what's going on, because I can't reproduce it.

**Comment by jameszlj** [comment]
yes spacy=2.1.8, but not good

**Comment by honnibal** [comment]
Is there a reason you're loading the model from disk, rather than from the installed package? What happens if you do:

```
import spacy
nlp = spacy.load("en_pytt_bertbaseuncased_lg")
```

**Comment by jameszlj** [comment]
> Is there a reason you're loading the model from disk, rather than from the installed package? What happens if you do:
> 
> ```
> import spacy
> nlp = spacy.load("en_pytt_bertbaseuncased_lg")
> ```

try this way .
>>> import spacy
>>> nlp = spacy.load("en_pytt_bertbaseuncased_lg")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Win10\Envs\Fine_py3\lib\site-packages\spacy\__init__.py", line 27, in load
    return util.load_model(name, **overrides)
  File "C:\Users\Win10\Envs\Fine_py3\lib\site-packages\spacy\util.py", line 134, in load_model
    return load_model_from_package(name, **overrides)
  File "C:\Users\Win10\Envs\Fine_py3\lib\site-packages\spacy\util.py", line 155, in load_model_from_package
    return cls.load(**overrides)
  File "C:\Users\Win10\Envs\Fine_py3\lib\site-packages\en_pytt_bertbaseuncased_lg\__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "C:\Users\Win10\Envs\Fine_py3\lib\site-packages\spacy\util.py", line 196, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "C:\Users\Win10\Envs\Fine_py3\lib\site-packages\spacy\util.py", line 179, in load_model_from_path
    return nlp.from_disk(model_path)
  File "C:\Users\Win10\Envs\Fine_py3\lib\site-packages\spacy\language.py", line 836, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "C:\Users\Win10\Envs\Fine_py3\lib\site-packages\spacy\util.py", line 636, in from_disk
    reader(path / key)
  File "C:\Users\Win10\Envs\Fine_py3\lib\site-packages\spacy\language.py", line 831, in <lambda>
    p, exclude=["vocab"]
  File "pipes.pyx", line 222, in spacy.pipeline.pipes.Pipe.from_disk
  File "C:\Users\Win10\Envs\Fine_py3\lib\site-packages\spacy\util.py", line 636, in from_disk
    reader(path / key)
  File "pipes.pyx", line 213, in spacy.pipeline.pipes.Pipe.from_disk.load_model
  File "C:\Users\Win10\Envs\Fine_py3\lib\site-packages\thinc\neural\_classes\model.py", line 362, in from_bytes
    layer.from_bytes(weights[i])
  File "C:\Users\Win10\Envs\Fine_py3\lib\site-packages\spacy_pytorch_transformers\wrapper.py", line 259, in from_bytes
    filelike = BytesIO(data)
TypeError: a bytes-like object is required, not 'dict'


**Whether it's the reason for the system or not, Linux system is fine**

**Comment by jameszlj** [comment]
> > Is there a reason you're loading the model from disk, rather than from the installed package? What happens if you do:
> > ```
> > import spacy
> > nlp = spacy.load("en_pytt_bertbaseuncased_lg")
> > ```
> 
> try this way .
> 
> > > > import spacy
> > > > nlp = spacy.load("en_pytt_bertbaseuncased_lg")
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > File "C:\Users\Win10\Envs\Fine_py3\lib\site-packages\spacy__init__.py", line 27, in load
> > > > return util.load_model(name, **overrides)
> > > > File "C:\Users\Win10\Envs\Fine_py3\lib\site-packages\spacy\util.py", line 134, in load_model
> > > > return load_model_from_package(name, **overrides)
> > > > File "C:\Users\Win10\Envs\Fine_py3\lib\site-packages\spacy\util.py", line 155, in load_model_from_package
> > > > return cls.load(**overrides)
> > > > File "C:\Users\Win10\Envs\Fine_py3\lib\site-packages\en_pytt_bertbaseuncased_lg__init__.py", line 12, in load
> > > > return load_model_from_init_py(**file**, **overrides)
> > > > File "C:\Users\Win10\Envs\Fine_py3\lib\site-packages\spacy\util.py", line 196, in load_model_from_init_py
> > > > return load_model_from_path(data_path, meta, **overrides)
> > > > File "C:\Users\Win10\Envs\Fine_py3\lib\site-packages\spacy\util.py", line 179, in load_model_from_path
> > > > return nlp.from_disk(model_path)
> > > > File "C:\Users\Win10\Envs\Fine_py3\lib\site-packages\spacy\language.py", line 836, in from_disk
> > > > util.from_disk(path, deserializers, exclude)
> > > > File "C:\Users\Win10\Envs\Fine_py3\lib\site-packages\spacy\util.py", line 636, in from_disk
> > > > reader(path / key)
> > > > File "C:\Users\Win10\Envs\Fine_py3\lib\site-packages\spacy\language.py", line 831, in 
> > > > p, exclude=["vocab"]
> > > > File "pipes.pyx", line 222, in spacy.pipeline.pipes.Pipe.from_disk
> > > > File "C:\Users\Win10\Envs\Fine_py3\lib\site-packages\spacy\util.py", line 636, in from_disk
> > > > reader(path / key)
> > > > File "pipes.pyx", line 213, in spacy.pipeline.pipes.Pipe.from_disk.load_model
> > > > File "C:\Users\Win10\Envs\Fine_py3\lib\site-packages\thinc\neural_classes\model.py", line 362, in from_bytes
> > > > layer.from_bytes(weights[i])
> > > > File "C:\Users\Win10\Envs\Fine_py3\lib\site-packages\spacy_pytorch_transformers\wrapper.py", line 259, in from_bytes
> > > > filelike = BytesIO(data)
> > > > TypeError: a bytes-like object is required, not 'dict'
> 
> **Whether it's the reason for the system or not, Linux system is fine**

_I'll download the model(en_pytt_bertbaseuncased_lg=2.1.1) again, all right._

thank you

**Comment by jameszlj** [comment]
Solve the problem
