### ISSUE TITLE
Spacy named entity extraction training on distillbert fails with TypeError: begin_training() takes at least 1 positional argument (0 given)

### ISSUE THREAD

**Issue by ghost1917** [explosion/spacy-pytorch-transformers#75]
I am trying to run the spacy NER training example [train_new_entity_type.py](https://github.com/explosion/spaCy/blob/master/examples/training/train_new_entity_type.py) with the distillbert model.

Training execution with the default spacy models works fine
```
python -m spacy download en_core_web_sm
python original_train_ner_entity_type.py -m en_core_web_sm
```

Execution with distillbert fails with an exception.
```
python -m spacy download en_pytt_distilbertbaseuncased_lg
python original_train_ner_entity_type.py -m en_pytt_distilbertbaseuncased_lg
```

```
Loaded model 'en_pytt_distilbertbaseuncased_lg'                                         
Traceback (most recent call last):                                                      
  File "original_train_ner_entity_type.py", line 138, in <module>                                                                                         e                     
    plac.call(main)                                                                     
  File "/opt/conda/envs/spacy_ner/lib/python3.7/site-packages/plac_core.py", line 328, in call                                                                          
    cmd, result = parser.consume(arglist)                                               
  File "/opt/conda/envs/spacy_ner/lib/python3.7/site-packages/plac_core.py", line 207, in consume   
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)                                                                                      
  File "original_train_ner_entity_type.py", line 95, in main                                                                                            
    optimizer = nlp.resume_training()
  File "/opt/conda/envs/spacy_ner/lib/python3.7/site-packages/spacy_pytorch_transformers/language.py", line 147, in resume_training
    component.begin_training(pipeline=self.pipeline, sgd=False, **cfg)
  File "nn_parser.pyx", line 568, in spacy.syntax.nn_parser.Parser.begin_training
TypeError: begin_training() takes at least 1 positional argument (0 given)
```

Python environment:
```
name: spacy_ner
channels:
  - defaults
dependencies:
  - scikit-learn==0.20.3
  - python==3.7
  - pip:
    - spacy-pytorch-transformers==0.4.0
prefix: /opt/conda/envs/spacy_ner
```

**Comment by ines** [comment]
We currently don't have an NER model implementation for transformer models – see @honnibal's [comment](https://github.com/explosion/spacy-pytorch-transformers/issues/23#issuecomment-526732208) in #23. 

So the example wouldn't work – you wouldn't be training an NER model using the transformer weights anyways.

**Comment by wahid18benz** [comment]
Hello @ines, please is it now available to train NER model using transformers ?
